<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>False</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Resources\Icons\appicon.ico</ApplicationIcon>
    <Copyright>HN Software development</Copyright>
    <PackageIcon>Resources\Icons\appicon.png</PackageIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <PublishReadyToRun>true</PublishReadyToRun>
    <AssemblyVersion>26.2.116.0</AssemblyVersion>
    <FileVersion>26.2.116.0</FileVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;1006</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;1006</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Fonts\Fredoka.ttf" />
    <None Remove="Resources\Icons\calendar.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="MySql.Data" Version="9.5.0" />
    <PackageReference Include="Syncfusion.DataGridExcelExport.Wpf" Version="32.1.21" />
    <PackageReference Include="Syncfusion.GridExcelExport.Wpf" Version="32.1.21" />
    <PackageReference Include="Syncfusion.Licensing" Version="32.1.21" />
    <PackageReference Include="Syncfusion.PivotTableExport.Wpf" Version="32.1.21" />
    <PackageReference Include="Syncfusion.SfGrid.WPF" Version="32.1.21" />
    <PackageReference Include="Syncfusion.SfNavigationDrawer.WPF" Version="32.1.21" />
    <PackageReference Include="Syncfusion.Shared.WPF" Version="32.1.21" />
    <PackageReference Include="Syncfusion.Tools.WPF" Version="32.1.21" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    <PackageReference Include="Syncfusion.XlsIO.Wpf" Version="32.1.21" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Cursors\exporting.ani" />
    <Resource Include="Resources\Fonts\Fredoka.ttf" />
    <Resource Include="Resources\Icons\calendar.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Languages\Language.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Language.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Languages\Language.resx">
      <Generator>publicResXFileCodeGenerator</Generator>
      <LastGenOutput>Language.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Modelbouwer.Resources.Languages</CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\Config\modelbouwer.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
