<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>False</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Resources\Icons\appicon.ico</ApplicationIcon>
    <Copyright>HN Software development</Copyright>
    <PackageIcon>Resources\Icons\appicon.png</PackageIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;1006</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;1006</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="MySql.Data" Version="9.5.0" />
    <PackageReference Include="Syncfusion.Licensing" Version="31.2.5" />
    <PackageReference Include="Syncfusion.SfGrid.WPF" Version="31.2.5" />
    <PackageReference Include="Syncfusion.SfNavigationDrawer.WPF" Version="31.2.5" />
    <PackageReference Include="Syncfusion.Shared.WPF" Version="31.2.5" />
    <PackageReference Include="Syncfusion.Tools.WPF" Version="31.2.5" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Languages\Language.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Language.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Languages\Language.resx">
      <Generator>publicResXFileCodeGenerator</Generator>
      <LastGenOutput>Language.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Modelbouwer.Resources.Languages</CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\Config\modelbouwer.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
