databaseType = "MySql"
id = "15dc97a5-d2c1-412e-ac4e-90862c996625"
name = "Modelbouwer"

[flyway]
callbackLocations = [ "filesystem:callbacks" ]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.mysql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.modelbuildertest]
url = "jdbc:mysql://localhost:3306"
schemas = [ "modelbuildertest" ]
displayName = "Modelbuilder Test"

[environments.target2]
url = "jdbc:mysql://87.210.244.108:3306"
schemas = [ "modelbuilder" ]
displayName = "NAS Database"
